[project]
name = "workflow-nuvs"
version = "0.1.0"
description = "A workflow for identifying novel viruses in Virtool."
readme = "README.md"
authors = [
    {name="Ian Boyes"},
    {name="Reece Hoffmann"},
    {name="Blake Smith"},
    {name="Tiansheng Sui"},
    {name="Elizabeth Roberts"},
    {name="Markus Swoveland"},
    {name="Christine Wong Chong"},
]
requires-python = ">=3.13.7,<4.0.0"
dependencies = [
    "virtool",
]

[dependency-groups]
dev = [
    "pydantic-factories>=1.17.3",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-mock>=3.14.1",
    "ruff>=0.15.21",
    "syrupy>=4.9.1",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["ANN201", "ANN202", "D205", "S101", "S106"]

[tool.uv.sources]
virtool = { git = "https://github.com/virtool/virtool", tag = "39.63.0" }
