name: CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: ghcr.io

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: commitlint
        uses: wagoid/commitlint-github-action@v5
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: base
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: workflow-nuvs:base
  test:
    name: "Test"  
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Mise
        uses: jdx/mise-action@v3
      - name: Test
        run: mise run test
  release:
    name: "Release"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [test, commitlint]
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      git-tag: ${{ steps.semantic.outputs.git-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
      - name: Install semantic-release
        run: npm i semantic-release@v24.2.5 @semantic-release/exec@v7.1.0 conventional-changelog-conventionalcommits@9.0.0
      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  ghcr:
    name: "Publish / GHCR"
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'Virtool' &&
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      needs.release.outputs.git-tag != ''
    needs: [release]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ needs.release.outputs.git-tag }}
      - name: Write VERSION file
        run: echo ${{ needs.release.outputs.git-tag }} > VERSION
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: git
          images: ${{ env.REGISTRY }}/virtool/nuvs
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
