name: CI

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.9-buster

    services:
      redis:
        image: redis:6.0
      mongo:
        image: mongo:4.4

    steps:
      - uses: actions/checkout@v2

      - name: Install tox
        run: pip install tox

      - name: Install Bowtie2
        run: |
          wget https://github.com/BenLangmead/bowtie2/releases/download/v2.3.2/bowtie2-2.3.2-legacy-linux-x86_64.zip
          unzip bowtie2-2.3.2-legacy-linux-x86_64.zip
          cp bowtie2-2.3.2-legacy/bowtie2* /usr/local/bin

      - name: Install HMMER
        run: |
          wget http://eddylab.org/software/hmmer/hmmer-3.2.1.tar.gz
          tar -xf hmmer-3.2.1.tar.gz
          cd hmmer-3.2.1
          ./configure --prefix /hmmer
          make
          make install

      - name: Install SPAdes
        run: |
          wget https://github.com/ablab/spades/releases/download/v3.11.0/SPAdes-3.11.0-Linux.tar.gz
          tar -xvf SPAdes-3.11.0-Linux.tar.gz
          mv SPAdes-3.11.0-Linux /spades

      - name: Run tox
        run:
          export PATH=$PATH:/hmmer/bin
          export PATH=$PATH:/spades/bin
          tox
