name: ci

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: commitlint
        uses: wagoid/commitlint-github-action@v5
  test:
    runs-on: ubuntu-22.04
    env:
        USER_ID: 1001
        GROUP_ID: 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compose Build
        run: docker-compose build --progress=plain
      - name: Compose Up
        run: docker-compose up -d
      - name: Test
        run: docker compose exec app poetry run pytest
  release:
    runs-on: ubuntu-22.04
    needs: [test, commitlint]
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install semantic-release
        run: npm i semantic-release@v23.0.0 conventional-changelog-conventionalcommits@7.0.2
      - name: Release
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
